# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to get all locations
#' @param max_sec maxsec
#' @param times tt
#' @param antennae aa
#' @param site_map sm
#' @return vector of sites
#' @export
get_all_locations_cpp <- function(start_time, end_time, times, antennae, site_map, prev_day_location) {
    .Call(`_stickleR_get_all_locations_cpp`, start_time, end_time, times, antennae, site_map, prev_day_location)
}

#' function to get all locations
#' @param times tt
#' @param location location
#' @param fish fish
#' @return vector of sites
#' @export
make_matrix_class <- function(times, location, fish, num_fish) {
    .Call(`_stickleR_make_matrix_class`, times, location, fish, num_fish)
}

